"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { frameUrl, liveCandidates } from "@/lib/api";
import type { PersonaConfig } from "@/lib/contract";
import type { PersonaState } from "@/lib/fleet-store";
import { toRow, type StreamRow } from "@/lib/codex";
import { kTokens, usd } from "@/lib/format";
import { useDialogFocus } from "@/lib/use-dialog-focus";
import { Avatar, SeverityChip, StatusChip, Segmented } from "@/components/ui";
import { LiveImage } from "./LiveImage";
import { useSession } from "./useSession";
export function ExpandedPane({ runId, p, config, onClose, onPrev, onNext }: { runId: string; p: PersonaState; config?: PersonaConfig; onClose: () => void; onPrev: () => void; onNext: () => void }) {
  const name = config?.name ?? p.id;
  const { events, connected } = useSession(runId, p.id);
  const dialogRef = useDialogFocus();
  const [tab, setTab] = useState<"activity" | "findings" | "raw">("activity");
  const [filter, setFilter] = useState<"all" | "reasoning" | "tool" | "telemetry">("all");
  const [viewFrame, setViewFrame] = useState<string | null>(null);
  const [autoScroll, setAutoScroll] = useState(true);
  const streamRef = useRef<HTMLDivElement>(null);
  const rows = useMemo(() => events.map(toRow).filter((r): r is StreamRow => r !== null), [events]);
  const visible = rows.filter(r => filter === "all" || r.kind === filter || filter === "reasoning" && r.kind === "message");
  const frames = useMemo(() => events.flatMap(ev => ev.kind === "action" && ev.frame && frameUrl(runId, ev.frame, p.id) ? [{ ref: ev.frame, step: ev.step }] : []), [events, runId, p.id]);
  const findings = useMemo(() => { const seen = new Map(p.findings.map(f => [f.id, f])); for (const ev of events) if (ev.kind === "finding") seen.set(ev.finding.id, ev.finding); return [...seen.values()]; }, [events, p.findings]);
  useEffect(() => { if (autoScroll && streamRef.current) streamRef.current.scrollTop = streamRef.current.scrollHeight; }, [rows.length, autoScroll, filter, tab]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); if ((e.target as HTMLElement)?.closest("input,textarea,select,button,summary")) return; if (e.key === "ArrowLeft") onPrev(); if (e.key === "ArrowRight") onNext(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [onClose, onPrev, onNext]);
  const lives = liveCandidates(p.liveUrl || `/api/runs/${runId}/${p.id}/live`, 0);
  const download = () => { const url = URL.createObjectURL(new Blob([events.map(e => JSON.stringify(e)).join("\n")], { type: "application/x-ndjson" })); const a = document.createElement("a"); a.href = url; a.download = `${p.id}-session.jsonl`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <div ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label={`${name} session details`} className="session-dialog-backdrop" data-expanded={p.id} onClick={onClose}>
    <div className="session-dialog" onClick={e => e.stopPropagation()}>
      <header className="session-dialog-header"><Avatar id={p.id} name={name} size={36}/><div className="min-w-0 flex-1"><h2 className="font-semibold text-lg">{name}</h2><p className="text-[13px] text-muted">{config?.goal ?? "Session details"}</p></div><StatusChip status={p.status}/><div className="flex gap-2"><button className="dialog-control" onClick={onPrev} aria-label="Previous tester">←</button><button className="dialog-control" onClick={onNext} aria-label="Next tester">→</button><button className="dialog-control" onClick={onClose} aria-label="Close session details">✕</button></div></header>
      <div className="session-dialog-body">
        <div className="session-media-column"><div className="flex justify-between items-center px-4 py-3 border-b border-line"><h3 className="text-sm font-semibold">{viewFrame ? "Recorded screenshot" : "Game view"}</h3>{viewFrame ? <button className="text-button" onClick={() => setViewFrame(null)}>Back to live view</button> : <span className="text-xs text-muted">{["done","stopped","failed"].includes(p.status) ? "Session ended" : "Live view"}</span>}</div><div className="session-large-image">{viewFrame ? <img src={viewFrame} alt="Selected screenshot from the tester’s session" className="absolute inset-0 h-full w-full object-contain"/> : <LiveImage srcs={lives} active={p.status !== "queued"} fit="contain" className="absolute inset-0 h-full w-full" alt={`${name} live game view`}/>}</div>
        <div className="p-4 border-t border-line"><h3 className="text-sm font-semibold">Tester screenshots <span className="text-muted font-normal">({frames.length})</span></h3><p className="text-xs text-muted mt-1">Select a screenshot to inspect exactly what this tester saw.</p><div className="mt-3 flex gap-2 overflow-x-auto pb-2" data-frames>{!frames.length && <p className="text-sm text-muted">No screenshots recorded yet.</p>}{frames.map((f,i) => { const url = frameUrl(runId,f.ref,p.id)!; return <button key={`${f.ref}-${i}`} onClick={() => setViewFrame(url)} aria-label={`View screenshot at action ${f.step}`} aria-pressed={viewFrame === url} className={`shrink-0 rounded border p-1 ${viewFrame === url ? "border-info bg-info/5" : "border-line"}`}><img src={url} alt={`Action ${f.step}`} loading="lazy" className="h-14 w-24 object-contain bg-[#111923]"/><span className="block text-xs mt-1 text-muted">Action {f.step}</span></button>; })}</div></div>
        <details className="border-t border-line p-4 text-sm"><summary className="font-semibold text-info">Tester profile & session totals <span aria-hidden="true">⌄</span></summary><p className="mt-3 text-muted leading-relaxed">{config?.bio}</p><dl className="detail-list mt-2"><div><dt>Actions taken</dt><dd>{p.steps}{config ? ` / ${config.enforcement.step_budget}` : ""}</dd></div><div><dt>Session cost</dt><dd>{usd(p.cost?.usd ?? 0)}</dd></div><div><dt>Input tokens</dt><dd>{kTokens(p.cost?.inputTokens ?? 0)}</dd></div>{config && <><div><dt>Reading</dt><dd>{config.enforcement.reading}</dd></div><div><dt>Audio</dt><dd>{config.enforcement.audio}</dd></div></>}</dl></details></div>
        <div className="session-activity-column"><div className="p-4 border-b border-line"><Segmented value={tab} options={["activity","findings","raw"] as const} labels={{ activity: "Activity", findings: `Findings (${findings.length})`, raw: "Raw data" }} onChange={setTab}/></div>
          {tab === "activity" && <><div className="flex justify-between gap-2 px-4 py-3 text-xs text-muted"><span>{connected ? "Live updates connected" : "Connecting to updates…"}</span><label className="flex items-center gap-2"><input type="checkbox" checked={autoScroll} onChange={e => setAutoScroll(e.target.checked)}/>Follow latest</label></div><div className="event-filter">{(["all","reasoning","tool","telemetry"] as const).map(v => <button key={v} aria-pressed={filter === v} onClick={() => setFilter(v)}>{({ all: "All activity", reasoning: "Tester thoughts", tool: "Actions", telemetry: "Game events" })[v]}</button>)}</div><div ref={streamRef} data-stream className="session-event-list" onScroll={e => { const el = e.currentTarget; if (el.scrollHeight-el.scrollTop-el.clientHeight > 50 && autoScroll) setAutoScroll(false); }}><ol>{visible.map((r,i) => <Row key={i} r={r}/>)}</ol>{!visible.length && <p className="text-sm text-muted p-4">No {filter === "all" ? "activity" : "matching events"} yet.</p>}</div></>}
          {tab === "findings" && <div className="session-event-list p-5 space-y-5">{!findings.length && <p className="text-sm text-muted">No findings reported yet. They will appear here as the tester plays.</p>}{findings.map(f => <article key={f.id} className="border-b border-line pb-5"><SeverityChip value={f.severity}/><h3 className="font-semibold text-base mt-3">{f.title}</h3><p className="text-sm leading-relaxed text-muted mt-2">{f.description}</p>{f.room && <p className="text-xs text-muted mt-2">Room: {f.room}</p>}<details className="mt-3 text-sm"><summary className="text-info">Steps to reproduce ⌄</summary><ol className="list-decimal pl-5 mt-2 space-y-2">{f.reproSteps.map((s,i) => <li key={i}>{s}</li>)}</ol></details></article>)}<Link className="text-info text-sm" href={`/runs/${runId}/report`}>Open full playtest report →</Link></div>}
          {tab === "raw" && <div className="session-event-list p-4"><div className="flex justify-between items-center mb-3"><span className="text-xs text-muted">{events.length} recorded events</span><button className="text-button" onClick={download}>Download JSONL</button></div><p className="text-sm text-muted mb-4">Complete recorded data, including game positions and system events.</p><pre className="text-xs leading-relaxed whitespace-pre-wrap break-all">{events.map(e => JSON.stringify(e)).join("\n") || "No events recorded yet."}</pre></div>}
        </div>
      </div>
    </div>
  </div>;
}
function Row({ r }: { r: StreamRow }) {
  const seconds = Math.floor(r.t/1000), time = `${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  const labels: Record<StreamRow["kind"],string> = { message: "Tester update", reasoning: "Tester thought", tool: "Action", finding: "Finding", gate: "Session limit", status: "Status", usage: "Token usage", telemetry: "Game event" };
  return <li className="event-row"><div className="flex justify-between gap-2 text-xs text-muted mb-2"><span className="font-semibold">{labels[r.kind]}</span><time className="tabular">{time}</time></div>{r.kind === "tool" ? <><p className="text-sm font-medium">{r.tool}{r.step !== undefined ? ` · Action ${r.step}` : ""}</p><details className="mt-2 text-xs"><summary className="text-info">Input & result ⌄</summary><pre className="mt-2 whitespace-pre-wrap break-all leading-relaxed bg-panel2 rounded p-3">{JSON.stringify({ args: r.args, result: r.result ?? null, frame: r.frame ?? null },null,2)}</pre></details></> : <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">{"text" in r ? r.text : r.kind === "finding" ? r.title : r.kind === "gate" ? r.detail : r.kind === "status" ? `${r.status}${r.detail ? `: ${r.detail}` : ""}` : r.kind === "usage" ? `${kTokens(r.input)} input · ${kTokens(r.cached)} cached · ${kTokens(r.output)} output` : ""}</p>}</li>;
}
